OWNER = []
OP = []

USERDATABASE = "USER"
PASSWORDDATABASE = ""
DATABASE = "DATABASE"
EMBEDFOOTERS = ''

PREFIX = '!'

is_maintenance = True
MAINTENANCE_AUTHORIZE = [OWNER[0]]
SERVER_WHITELISTED = []

TOKEN = 'TOKEN'